'use strict';

const express = require('express');
const { confirmRegistration } = require('../services/registrationService');
const logger = require('../config/logger');

const router = express.Router();

// ============================================================
// WALLETS API ROUTES (MOBILE APP / STUDENT FACING)
// All routes here must be protected by student authentication
// (e.g., JWT, Session) so we can securely extract the student ID.
// ============================================================

// ── Auth Middleware Placeholder ─────────────────────────────
// The dev must replace this with your actual student auth middleware.
// It MUST populate `req.user.id` or `req.student.id`.
const requireStudentAuth = (req, res, next) => {
  // Example implementation:
  // if (!req.user || !req.user.id) return res.status(401).json({ error: 'Unauthorized' });
  next(); // Placeholder allowing it to pass for now
};

router.use(requireStudentAuth);

// ── POST /link ──────────────────────────────────────────────
// Links a physical NFC/RFID card to the student's mobile account
// using the 6-digit OTP generated by the bus terminal.
router.post('/link', async (req, res) => {
  const { otp } = req.body;

  // Extract the secure ID from the authenticated session, NOT the request body.
  // The dev must adjust 'req.user.id' to match your actual auth payload structure.
  const studentId = req.user?.id || req.body?.mockStudentId; // Remove mock fallback in production

  if (!studentId) {
    logger.warn({ ip: req.ip }, 'wallets.link_failed_missing_auth');
    return res.status(401).json({ success: false, message: 'Unauthorized: Student ID missing from session' });
  }

  if (!otp) {
    return res.status(400).json({ success: false, message: 'OTP is required' });
  }

  try {
    // Pass to the business logic engine
    const result = await confirmRegistration(otp, studentId);

    if (result.success) {
      logger.info({ studentId }, 'wallets.card_linked_successfully');
      return res.status(200).json(result);
    }

    return res.status(400).json(result);
  } catch (err) {
    logger.error({ err: err.message, studentId }, 'wallets.link_error');
    return res.status(500).json({ success: false, message: 'Internal server error' });
  }
});

module.exports = router;
